export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE';
export const LIST_USER_FOLLOW_STORE = 'LIST_USER_FOLLOW_STORE';
export const FOLLOW_LIST_STORE = 'FOLLOW_LIST_STORE';
